version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: prov_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: provdb
      MARIADB_USER: larissa
      MARIADB_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: prov_adminer
    restart: always
    ports:
      - "8080:8080"
